# Generated by Django 4.2.16 on 2024-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('학교', models.CharField(max_length=50)),
                ('학년', models.IntegerField()),
                ('학기', models.IntegerField()),
                ('대단원명', models.CharField(max_length=255)),
                ('소단원명', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
