# Generated by Django 4.2.16 on 2024-09-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smp_django', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
