# Generated by Django 4.2.16 on 2024-09-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('학교', models.CharField(max_length=50)),
                ('학년', models.IntegerField()),
                ('대단원명', models.CharField(max_length=255)),
                ('소단원명', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('문제_경로', models.CharField(max_length=255)),
                ('해설_경로', models.CharField(max_length=255)),
                ('난이도', models.IntegerField()),
                ('문서_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_problems.chapter')),
            ],
        ),
    ]
